export const mockOrders = [
  {
    id: 'ord-001',
    orderNumber: 'PHL-2025-0041',
    treatmentName: 'Mounjaro KwikPen 5mg',
    description: 'Tirzepatide 5mg — 1 pen',
    status: 'ORDER_PLACED',
    price: '£169.00',
    orderedDate: '10 Apr 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-006',
    orderNumber: 'PHL-2025-0047',
    treatmentName: 'Wegovy 0.5mg',
    description: 'Semaglutide 0.5mg — 1 pen',
    status: 'ON_HOLD',
    price: '£199.00',
    orderedDate: '12 Apr 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-007',
    orderNumber: 'PHL-2025-0033',
    treatmentName: 'Mounjaro KwikPen 2.5mg',
    description: 'Tirzepatide 2.5mg — 1 pen',
    status: 'PAYMENT_FAILED',
    price: '£149.00',
    orderedDate: '8 Mar 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-008',
    orderNumber: 'PHL-2025-0051',
    treatmentName: 'Mounjaro KwikPen 5mg',
    description: 'Tirzepatide 5mg — 1 pen',
    status: 'IN_REVIEW_NO_ACTION',
    price: '£169.00',
    orderedDate: '14 Apr 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-009',
    orderNumber: 'PHL-2025-0044',
    treatmentName: 'Wegovy 0.25mg',
    description: 'Semaglutide 0.25mg — 1 pen',
    status: 'IN_REVIEW_EVIDENCE_REQUIRED',
    price: '£189.00',
    orderedDate: '11 Apr 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-010',
    orderNumber: 'PHL-2025-0038',
    treatmentName: 'Mounjaro KwikPen 2.5mg',
    description: 'Tirzepatide 2.5mg — 1 pen',
    status: 'IN_REVIEW_UPLOADED',
    price: '£149.00',
    orderedDate: '9 Apr 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-002',
    orderNumber: 'PHL-2025-0028',
    treatmentName: 'Mounjaro KwikPen 2.5mg',
    description: 'Tirzepatide 2.5mg — 1 pen',
    status: 'PRESCRIBER_REVIEW',
    price: '£149.00',
    orderedDate: '10 Mar 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-003',
    orderNumber: 'PHL-2025-0019',
    treatmentName: 'Mounjaro KwikPen 2.5mg',
    description: 'Tirzepatide 2.5mg — 1 pen',
    status: 'PREPARING_YOUR_ORDER',
    price: '£149.00',
    orderedDate: '10 Feb 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-011',
    orderNumber: 'PHL-2025-0029',
    treatmentName: 'Mounjaro KwikPen 2.5mg',
    description: 'Tirzepatide 2.5mg — 1 pen',
    status: 'REJECTED',
    price: '£149.00',
    orderedDate: '5 Feb 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-013',
    orderNumber: 'PHL-2025-0021',
    treatmentName: 'Wegovy 0.25mg',
    description: 'Semaglutide 0.25mg — 1 pen',
    status: 'CANCELLED',
    price: '£189.00',
    orderedDate: '3 Feb 2025',
    deliveryDate: null,
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-004',
    orderNumber: 'PHL-2025-0055',
    treatmentName: 'Wegovy 0.25mg',
    description: 'Semaglutide 0.25mg — 1 pen',
    status: 'DISPATCHED',
    price: '£189.00',
    orderedDate: '22 Apr 2025',
    deliveryDate: '28 Apr 2025',
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-005',
    orderNumber: 'PHL-2025-0062',
    treatmentName: 'Mounjaro KwikPen 5mg',
    description: 'Tirzepatide 5mg — 3 pens',
    status: 'DELIVERED',
    price: '£469.00',
    orderedDate: '25 Apr 2025',
    deliveryDate: '28 Apr 2025',
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
  {
    id: 'ord-012',
    orderNumber: 'PHL-2025-0015',
    treatmentName: 'Mounjaro KwikPen 2.5mg',
    description: 'Tirzepatide 2.5mg — 1 pen',
    status: 'DELIVERED_CONFIRMED',
    price: '£149.00',
    orderedDate: '10 Jan 2025',
    deliveryDate: '14 Jan 2025',
    address: '14 Rosewood Avenue, London, SW4 7BN',
    bannerText: null,
    bannerVariant: null,
  },
] as const;

export type MockOrder = typeof mockOrders[number];

export const mockWeightHistory = [
  { id: 'wh-1', weight_lbs: 180.8, weight_kg: 82.0, date: new Date('2025-04-10'), type: 'check-in' as const, verified: false },
  { id: 'wh-2', weight_lbs: 183.4, weight_kg: 83.2, date: new Date('2025-03-10'), type: 'check-in' as const, verified: true },
  { id: 'wh-3', weight_lbs: 186.1, weight_kg: 84.4, date: new Date('2025-02-10'), type: 'check-in' as const, verified: false },
  { id: 'wh-4', weight_lbs: 190.5, weight_kg: 86.4, date: new Date('2025-01-15'), type: 'starting-weight' as const, verified: false },
];

export const mockPatient = {
  firstName: 'Sarah',
  lastName: 'Mitchell',
  email: 'sarah.mitchell@example.com',
  mobile: '+44 7700 900123',
  dob: '15/06/1988',
  addressLine1: '14 Rosewood Avenue',
  city: 'London',
  postcode: 'SW4 7BN',
};
